language: node_js
node_js:
  - "14"
cache:
  directories:
  - node_modules
script:
  - yarn test:unit
  - yarn build
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist
  on:
    branch: master
